---

- name: install dependent packages for red hat derivative distros
  yum: name={{item}} state=present
  with_items:
    - git-core
    - curl
    - gcc
    - glibc
    - make
    - autoconf
    - libselinux-python
    - ncurses-devel
    - openssl-devel
  when: ansible_os_family == 'RedHat'

- name: install dependent packages for debian derivative distros
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git-core
    - curl
    - gcc
    - libc6
    - make
    - autoconf
    - libncurses5-dev
    - openssl
    - libssl-dev
  when: ansible_os_family == 'Debian'
