---
galaxy_info:
  author: ohr486
  description: install elixir
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
  #  - all
    #- 5
    - 6
    - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  - name: Fedora
    versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
    - 20
  #- name: SmartOS
  #  versions:
  #  - all
  #  - any
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  - name: Amazon
    versions:
    - 2014.09.2
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  - name: Ubuntu
    versions:
  #  - all
  #  - lucid:10.04
  #  - maverick:10.10
  #  - natty:11.04
  #  - oneiric:11.10
  #  - precise:12.04
  #  - quantal:12.10
  #  - raring:13.04
  #  - saucy:13.10
    - trusty:14.04
    - vivid:15.04
    - wily:15.10
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  #- name: Debian
  #  versions:
  #  - all
  #  - etch:4.x
  #  - lenny:5.x
  #  - squeeze:6.x
  #  - wheezy:7.x

  categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
  - development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
